version: "3.1"
services:
    redis:
      image: redis:alpine
      container_name: wiseweb-cms-redis

    mariadb:
      image: mariadb:10.1
      container_name: wiseweb-cms-mariadb
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=test
        - MYSQL_DATABASE=test
        - MYSQL_USER=test
        - MYSQL_PASSWORD=test
      ports:
        - "1028:3306"

    webserver:
      image: nginx:alpine
      container_name: wiseweb-cms-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
          - ./phpdocker/nginx/ssl.conf:/etc/nginx/conf.d/ssl.conf
      ports:
          - "80:80"    
          - "443:443"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: wiseweb-cms-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php5/fpm/conf.d/99-overrides.ini

    composer:
        restart: 'no'
        image: composer/composer:php7
        command: install
        volumes:
            - .:/app

